### ISSUE TITLE
balenad crash-looping after 'os error 2'

### ISSUE THREAD

**Issue by markcorbinuk** [balena-os/balena-engine#259]
**Description**

The balena service reports an error when starting and eventually the process is killed by systemd after a 6 minute timeout. This behaviour keeps repeating in a loop.

Initial error:
```
Jul 09 14:36:18 467cf68 balenad[6789]: No such file or directory (os error 2)
```
After 6 minutes:
```
Jul 09 14:42:21 467cf68 systemd[1]: balena.service: Watchdog timeout (limit 6min)!
Jul 09 14:42:21 467cf68 systemd[1]: balena.service: Killing process 6788 (balenad) with signal SIGABRT.
Jul 09 14:42:21 467cf68 balenad[6788]: SIGABRT: abort
Jul 09 14:42:21 467cf68 balenad[6788]: PC=0x7275c m=0 sigcode=0
Jul 09 14:42:21 467cf68 balenad[6788]: goroutine 0 [idle]:
Jul 09 14:42:21 467cf68 balenad[6788]: runtime.futex(0x251cb74, 0x80, 0x0, 0x0, 0x0, 0x0, 0x1c501, 0x0, 0x0, 0x47b94, ...)
Jul 09 14:42:21 467cf68 balenad[6788]:         /usr/lib/go/src/runtime/sys_linux_arm.s:334 +0x1c
Jul 09 14:42:21 467cf68 balenad[6788]: runtime.futexsleep(0x251cb74, 0x0, 0xffffffff, 0xffffffff)
Jul 09 14:42:21 467cf68 balenad[6788]:         /usr/lib/go/src/runtime/os_linux.go:46 +0x7c
Jul 09 14:42:21 467cf68 balenad[6788]: runtime.notesleep(0x251cb74)
Jul 09 14:42:21 467cf68 balenad[6788]:         /usr/lib/go/src/runtime/lock_futex.go:151 +0xb4
Jul 09 14:42:21 467cf68 balenad[6788]: runtime.stopm()
Jul 09 14:42:21 467cf68 balenad[6788]:         /usr/lib/go/src/runtime/proc.go:1936 +0xa8
Jul 09 14:42:21 467cf68 balenad[6788]: runtime.findrunnable(0x4447300, 0x0)
Jul 09 14:42:21 467cf68 balenad[6788]:         /usr/lib/go/src/runtime/proc.go:2399 +0x418
Jul 09 14:42:21 467cf68 balenad[6788]: runtime.schedule()
Jul 09 14:42:21 467cf68 balenad[6788]:         /usr/lib/go/src/runtime/proc.go:2525 +0x20c
Jul 09 14:42:21 467cf68 balenad[6788]: runtime.park_m(0x4401180)
Jul 09 14:42:21 467cf68 balenad[6788]:         /usr/lib/go/src/runtime/proc.go:2605 +0x90
Jul 09 14:42:21 467cf68 balenad[6788]: runtime.mcall(0x6fb78)
Jul 09 14:42:21 467cf68 balenad[6788]:         /usr/lib/go/src/runtime/asm_arm.s:289 +0x5c
Jul 09 14:42:21 467cf68 balenad[6788]: goroutine 1 [chan receive, 6 minutes]:
Jul 09 14:42:21 467cf68 balenad[6788]: github.com/docker/docker/cmd/dockerd.(*DaemonCli).start(0x48b81c0, 0x45cd860, 0x0, 0x0)
Jul 09 14:42:21 467cf68 balenad[6788]:         /home/mark/balena-raspberrypi-hostname/build/tmp/work/cortexa7t2hf-neon-vfpv4-poky-linux-gnueabi/balena/19.03.18+git840aacc77b6c600b3b929fe9e4d9356a322b9e5>
Jul 09 14:42:21 467cf68 balenad[6788]: github.com/docker/docker/cmd/dockerd.runDaemon(...)
Jul 09 14:42:21 467cf68 balenad[6788]:         /home/mark/balena-raspberrypi-hostname/build/tmp/work/cortexa7t2hf-neon-vfpv4-poky-linux-gnueabi/balena/19.03.18+git840aacc77b6c600b3b929fe9e4d9356a322b9e5>
Jul 09 14:42:21 467cf68 balenad[6788]: github.com/docker/docker/cmd/dockerd.newDaemonCommand.func1(0x48b6000, 0x455c580, 0x0, 0x10, 0x0, 0x0)
Jul 09 14:42:21 467cf68 balenad[6788]:         /home/mark/balena-raspberrypi-hostname/build/tmp/work/cortexa7t2hf-neon-vfpv4-poky-linux-gnueabi/balena/19.03.18+git840aacc77b6c600b3b929fe9e4d9356a322b9e5>
Jul 09 14:42:21 467cf68 balenad[6788]: github.com/docker/docker/vendor/github.com/spf13/cobra.(*Command).execute(0x48b6000, 0x44a4098, 0x10, 0x11, 0x48b6000, 0x44a4098)
Jul 09 14:42:21 467cf68 balenad[6788]:         /home/mark/balena-raspberrypi-hostname/build/tmp/work/cortexa7t2hf-neon-vfpv4-poky-linux-gnueabi/balena/19.03.18+git840aacc77b6c600b3b929fe9e4d9356a322b9e5>
Jul 09 14:42:21 467cf68 balenad[6788]: github.com/docker/docker/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x48b6000, 0x0, 0x0, 0x10)
Jul 09 14:42:21 467cf68 balenad[6788]:         /home/mark/balena-raspberrypi-hostname/build/tmp/work/cortexa7t2hf-neon-vfpv4-poky-linux-gnueabi/balena/19.03.18+git840aacc77b6c600b3b929fe9e4d9356a322b9e5>
Jul 09 14:42:21 467cf68 balenad[6788]: github.com/docker/docker/vendor/github.com/spf13/cobra.(*Command).Execute(...)
Jul 09 14:42:21 467cf68 balenad[6788]:         /home/mark/balena-raspberrypi-hostname/build/tmp/work/cortexa7t2hf-neon-vfpv4-poky-linux-gnueabi/balena/19.03.18+git840aacc77b6c600b3b929fe9e4d9356a322b9e5>
Jul 09 14:42:21 467cf68 balenad[6788]: github.com/docker/docker/cmd/dockerd.Main()
Jul 09 14:42:21 467cf68 balenad[6788]:         /home/mark/balena-raspberrypi-hostname/build/tmp/work/cortexa7t2hf-neon-vfpv4-poky-linux-gnueabi/balena/19.03.18+git840aacc77b6c600b3b929fe9e4d9356a322b9e5>
Jul 09 14:42:21 467cf68 balenad[6788]: main.main()
Jul 09 14:42:21 467cf68 balenad[6788]:         /home/mark/balena-raspberrypi-hostname/build/tmp/work/cortexa7t2hf-neon-vfpv4-poky-linux-gnueabi/balena/19.03.18+git840aacc77b6c600b3b929fe9e4d9356a322b9e5>
Jul 09 14:42:21 467cf68 balenad[6788]: goroutine 19 [syscall, 6 minutes]:
Jul 09 14:42:21 467cf68 balenad[6788]: os/signal.signal_recv(0x0)
Jul 09 14:42:21 467cf68 balenad[6788]:         /usr/lib/go/src/runtime/sigqueue.go:139 +0x130
Jul 09 14:42:21 467cf68 balenad[6788]: os/signal.loop()
Jul 09 14:42:21 467cf68 balenad[6788]:         /usr/lib/go/src/os/signal/signal_unix.go:23 +0x14
Jul 09 14:42:21 467cf68 balenad[6788]: created by os/signal.init.0
Jul 09 14:42:21 467cf68 balenad[6788]:         /usr/lib/go/src/os/signal/signal_unix.go:29 +0x30
.
.
.
.
Jul 09 14:42:21 467cf68 balenad[6788]: trap    0x0
Jul 09 14:42:21 467cf68 balenad[6788]: error   0x0
Jul 09 14:42:21 467cf68 balenad[6788]: oldmask 0x0
Jul 09 14:42:21 467cf68 balenad[6788]: r0      0x251cb74
Jul 09 14:42:21 467cf68 balenad[6788]: r1      0x80
Jul 09 14:42:21 467cf68 balenad[6788]: r2      0x0
Jul 09 14:42:21 467cf68 balenad[6788]: r3      0x0
Jul 09 14:42:21 467cf68 balenad[6788]: r4      0x0
Jul 09 14:42:21 467cf68 balenad[6788]: r5      0x0
Jul 09 14:42:21 467cf68 balenad[6788]: r6      0x2
Jul 09 14:42:21 467cf68 balenad[6788]: r7      0xf0
Jul 09 14:42:21 467cf68 balenad[6788]: r8      0x7
Jul 09 14:42:21 467cf68 balenad[6788]: r9      0x41
Jul 09 14:42:21 467cf68 balenad[6788]: r10     0x251c8b8
Jul 09 14:42:21 467cf68 balenad[6788]: fp      0x7
Jul 09 14:42:21 467cf68 balenad[6788]: ip      0xfffffff8
Jul 09 14:42:21 467cf68 balenad[6788]: sp      0x7eb7e6a4
Jul 09 14:42:21 467cf68 balenad[6788]: lr      0x3fe8c
Jul 09 14:42:21 467cf68 balenad[6788]: pc      0x7275c
Jul 09 14:42:21 467cf68 balenad[6788]: cpsr    0x20070010
Jul 09 14:42:21 467cf68 balenad[6788]: fault   0x0
Jul 09 14:42:21 467cf68 systemd[1]: balena.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Jul 09 14:42:21 467cf68 systemd[1]: balena.service: Failed with result 'watchdog'.
Jul 09 14:42:22 467cf68 systemd[1]: balena.service: Found left-over process 7051 (balena-engine-c) in control group while starting unit. Ignoring.
Jul 09 14:42:22 467cf68 systemd[1]: This usually indicates unclean termination of a previous run, or service implementation deficiencies.
Jul 09 14:42:22 467cf68 systemd[1]: balena.service: Found left-over process 7403 (balena-engine-c) in control group while starting unit. Ignoring.
Jul 09 14:42:22 467cf68 systemd[1]: This usually indicates unclean termination of a previous run, or service implementation deficiencies.

```

**Output of `balena-engine version`:**

```
Client:
 Version:           19.03.18
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        840aacc77b6c600b3b929fe9e4d9356a322b9e5b
 Built:             Fri Jul  9 12:46:22 2021
 OS/Arch:           linux/arm
 Experimental:      false

Server:
 Engine:
  Version:          19.03.18
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       840aacc77b6c600b3b929fe9e4d9356a322b9e5b
  Built:            Fri Jul  9 12:46:22 2021
  OS/Arch:          linux/arm
  Experimental:     true
 containerd:
  Version:          1.2.0+unknown
  GitCommit:        
 runc:
  Version:          1.0.0-rc4+dev
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 balena-engine-init:
  Version:          0.13.0
  GitCommit:        949e6fa-dirty
```

**Output of `balena-engine info`:**

```
Client:
 Debug Mode: false

Server:
 Containers: 2
  Running: 2
  Paused: 0
  Stopped: 0
 Images: 3
 Server Version: 19.03.18
 Storage Driver: aufs
  Root Dir: /var/lib/docker/aufs
  Backing Filesystem: extfs
  Dirs: 45
  Dirperm1 Supported: true
 Logging Driver: journald
 Cgroup Driver: systemd
 Plugins:
  Volume: local
  Network: bridge host null
  Log: journald json-file local
 Swarm: 
  NodeID: 
  Is Manager: false
  Node Address: 
 Runtimes: bare runc
 Default Runtime: runc
 Init Binary: balena-engine-init
 containerd version: 
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: 949e6fa-dirty (expected: fec3683b971d9)
 Kernel Version: 5.4.83-v7
 Operating System: balenaOS 2.80.8+rev4
 OSType: linux
 Architecture: armv7l
 CPUs: 4
 Total Memory: 973.3MiB
 Name: 467cf68
 ID: B5BN:I6XY:QAN6:ZJNO:SB4Q:R4BW:ZFXB:6WFC:MTUP:ADHR:2ISL:2U72
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: true
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
WARNING: the aufs storage-driver is deprecated, and will be removed in a future release.
```

**Additional environment details (device type, OS, etc.):**
Raspberry Pi 3 B+
balenaOS 2.80.8+rev4
meta-balena 2.81.0

**Comment by klutchell** [comment]
This seems to be related to https://github.com/balena-os/meta-balena/pull/2245
