### ISSUE TITLE
Daemon errors with `(HTTP code 404) -- no such container: sandbox`

### ISSUE THREAD

**Issue by cywang117** [balena-os/balena-engine#261]
**Description**

balenaEngine daemon errors with (HTTP code 404) -- no such container: sandbox <HASH>. However, there is no `sandbox` container on the device. This error is communicated by the device Supervisor from the journal logs with:

`Device state apply error Error: Failed to apply state transition steps. (HTTP code 404) no such container - sandbox 915c9f1f78712e9db8bb1edf3d94fd669a917c608270f4c95e3a8c72de142b15 not found  Steps:["updateMetadata"]`

Per https://github.com/balena-io/balena-io/issues/1684, this might be due to a bad internal state with one of the containers on the device. The issue is fixed by restarting balenaEngine with `systemctl restart balena` OR `systemctl stop balena-supervisor && balena stop $(balena ps -a -q) && balena rm $(balena ps -a -q) && systemctl start balena-supervisor`, however this is not ideal as the containers experience a few minutes of downtime.

EDIT (same as my comment below): The fact that stopping the Supervisor, removing the containers, and starting the Supervisor fixes the issue seems to indicate that this is a Supervisor issue and not a balenaEngine issue. I originally created this issue in the balenaEngine repo but it seems that it's more appropriate here.

It's unclear how to reproduce this issue.

**Additional information you deem important (e.g. issue happens only occasionally):**

Issue happens when a new update is downloaded by the device. Has sometimes appeared in combination with balena-os/balena-supervisor#1579, making cause unclear.

**Additional environment details (device type, OS, etc.):**

Device Type: Raspberry Pi 4 64bit, 2GB RAM
OS: balenaOS 2.80.3+rev1.prod

**Comment by cywang117** [comment]
@lmbarros @robertgzr Drawing your attention to some edits I made to this GitHub issue:
> NOTE: For users and support agents arriving here in the future: since it's not clear how we can reproduce this issue, please find out more information about various conditions on the device. Some good starting questions and things to check:
> - Did this error appear after a release update?
> - Are deltas enabled?
> - Does the release build use intermediate containers? (If not sure, looking at the Dockerfile(s) of the containers would tell you)
> - Any other questions which you think might be relevant.
>
> Asking the user if they wouldn't mind leaving the device in this invalid state for engineers to investigate would also help, if the user is okay with this of course.

Are there any other questions that you think would be useful in investigating the causes behind this issue? Could this kind of problem be something that is unavoidable based on current implementation limitations in dependencies (Moby)?

**Comment by pipex** [comment]
Some extra information for this ticket, this has been reported to be happening more with containers that don't get updated as frequently as others. So a container that has been renamed a few times while others have been recreated may sometimes get into this state

For instance, for a particular device, the failing container shows a network prefix of 16

```
root@4cd008d3ffa1:/opt# ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
15: eth0@if16: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default 
    link/ether 02:42:ac:11:00:05 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 172.17.0.5/16 brd 172.17.255.255 scope global eth0
       valid_lft forever preferred_lft forever
```

While other veth networks have a much larger prefix, confirming that this is an old network.

```
root@c73b31f:~# ip a | grep veth
1291: veth6f7ff99@if1290: <BROADCAST,MULTICAST,UP,LOWER_UP,M-DOWN> mtu 1500 qdisc noqueue master br-2f18a4b13b86 
16: veth367da35@if15: <BROADCAST,MULTICAST,UP,LOWER_UP,M-DOWN> mtu 1500 qdisc noqueue master br-2f18a4b13b86 
1380: veth72261a3@if1379: <BROADCAST,MULTICAST,UP,LOWER_UP,M-DOWN> mtu 1500 qdisc noqueue master br-2f18a4b13b86 
1180: vethe52f1a4@if1179: <BROADCAST,MULTICAST,UP,LOWER_UP,M-DOWN> mtu 1500 qdisc noqueue master br-2f18a4b13b86
```

Could  this issue be an unintended side effect of some cleanup process?

**Comment by vipulgupta2048** [comment]
Did this error appear after a release update? Yep
Are deltas enabled? Yes
Does the release build use intermediate containers?  Indeed, 2 stages 

Happened on a new device with just the second release I pushed on it, running a minimal server application (200 mb image, 2 stage build process). Error is below: 

```
Jun 02 20:25:35 a01a838 balena-supervisor[2376]: [info]    Applying target state
Jun 02 20:25:36 a01a838 balena-supervisor[2376]: [error]   Scheduling another update attempt in 1000ms due to failure:  Error: Failed to appl>
Jun 02 20:25:36 a01a838 balena-supervisor[2376]: [error]         at fn (/usr/src/app/dist/app.js:6:8690)
Jun 02 20:25:36 a01a838 balena-supervisor[2376]: [error]   Device state apply error Error: Failed to apply state transition steps. (HTTP code>
Jun 02 20:25:36 a01a838 balena-supervisor[2376]: [error]         at fn (/usr/src/app/dist/app.js:6:8690)
Jun 02 20:25:37 a01a838 balena-supervisor[2376]: [info]    Applying target state
Jun 02 20:25:38 a01a838 balena-supervisor[2376]: [error]   Scheduling another update attempt in 2000ms due to failure:  Error: Failed to appl>
Jun 02 20:25:38 a01a838 balena-supervisor[2376]: [error]         at fn (/usr/src/app/dist/app.js:6:8690)
Jun 02 20:25:38 a01a838 balena-supervisor[2376]: [error]   Device state apply error Error: Failed to apply state transition steps. (HTTP code>
Jun 02 20:25:38 a01a838 balena-supervisor[2376]: [error]         at fn (/usr/src/app/dist/app.js:6:8690)
Jun 02 20:25:40 a01a838 balena-supervisor[2376]: [info]    Applying target state
```

Attaching diagnostics File: [a01a83846e174aa51dc2b33fbf0a17e7_diagnostics_2022.06.02_20.56.19+0000.txt](https://github.com/balena-os/balena-engine/files/8827774/a01a83846e174aa51dc2b33fbf0a17e7_diagnostics_2022.06.02_20.56.19%2B0000.txt)
